Error: Command failed with exit code 255: C:\Users\Minjinsor\anaconda3\envs\DVC\python.exe -m dvc dag --md
ERROR: The output paths:
'data'('data.dvc')
'data\prepared'('prepare')
overlap and are thus in the same tracked directory.
To keep reproducibility, outputs should be in separate tracked directories or tracked individually.